name: AskMyCompany Deployment

on:
  push:
    branches: [ "main" ]

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: echo "Add tests here!"

    - name: Build Docker Image
      run: docker build -t askmycompany .

    - name: Run container (optional)
      run: docker run -d -p 8501:8501 askmycompany
